CHANGELOG.md, README.md, honeybadger.js, spec/honeybadger.spec.js
This allows the user to include cookies and params manually when calling `Honeybadger.notify`:
```js
// Sending params
Honeybadger.notify("testing", {
params: {
foo: 'bar'
}
});
// Sending cookies as string (i.e. in the format of `document.cookie`)
Honeybadger.notify("testing", {
cookies: 'foo=bar'
});
// Sending cookies as an object
Honeybadger.notify("testing", {
cookies: {
foo: 'bar'
}
});
```
Using this method, you can also configure honeybadger.js to always send cookies:
```js
Honeybadger.beforeNotify(function(err){
err.cookies = document.cookie;
return true;
})
```
=> Add cookies and params options to ::notify()

README.md, honeybadger.js
We had a situation where we needed to send a Honeybadger notification right before a hard redirect, but as soon as the redirect occurred any XHR requests in progress were cancelled and the notification would never be sent. 
This option allows us to force the request to be synchronous, ensuring that it is send before the redirect happens.
=> Add 'async' configuration

honeybadger.js
We have an  issue when use ruby assets and compile the library with other libraries with `'use strict';`. It would great to have proper JS here also to not have exception like `i is not declared`
=> Strict mode

honeybadger-js.d.ts, package.json
This will be very handy for your typescript users (myself included). It allows a user to have access to all of the types in Honeybadger with no configuration at all.
Let me know what you think!
=> Add type declarations for TypeScript

README.md
This doesn't seem to be mentioned on the [documentation site](http://docs.honeybadger.io/lib/javascript.html) or in the `README.md`... not sure if that's intentional.
=> Documents the debug configuration option

honeybadger.js, spec/honeybadger.spec.js
Some third party ad libraries pass [frozen](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) functions to setTimeout which results in errors in console and broken functionality.
If function passed to `wrap` is sealed or frozen, fn.__hb would still be undefined after [assignment](https://github.com/honeybadger-io/honeybadger-js/blob/master/honeybadger.js#L357).
=> Wrap function: don't try to extend non-extensible object

README.md, honeybadger.js, spec/honeybadger.spec.js
Allow the user to provide `ignorePatterns` as an array of regexes. Any
error whose message matches one of these patterns will not trigger a
notification.
Re: issue #6
=> Allow error messages to be ignored

honeybadger.js
When disabled is set to true (we don't want to send the request to notify), we are not outputting the error in development mode even if debug option was set to true.  The reason being is that we are halting too early.
Halt later in the process. Specifically, any time we try to do a request, if disabled is true, don't do it.
=> Don't send request if disabled is true

CHANGELOG.md, honeybadger.js, spec/honeybadger.spec.js
See the CHANGELOG for details. Fixes #75
=> Make Honeybadger.wrap() idempotent.

honeybadger.js
We've been trying to use the `honeybadger-js` library from ClojureScript. One problem we ran into was that the Google Closure compiler was renaming the properties of the payload object before it was sent to the API.
This PR changes the payload to use quoted object properties so that Google Closure will not try to optimize it. This enables the library to work with ClojureScript without breaking any existing behavior.
=> Fix for Google Closure advanced compilation

honeybadger.js
See the commit messages for each of the commits in this PR, which fix specific aspects of this issue. This reverts the behavior added in #88/#92 and takes a different approach.
This PR does not fix the context for `this` being undefined in certain environments inside the factory builder function (see #89); instead, it relies directly on `window` for objects which depend on `window`, rather than assuming that `this` is window inside the function. We're already using this approach elsewhere in the factory (for instance, in `Honeybadger.notify`), so I think it's fairly safe. If we need to revisit this in the future, we can do it as a whole.
This should also fix #94 and #95.
cc @geoffreak @monde @stympy @rathboma @kellym @shahen94 -- lmk what you think.
=> Fix continuing issues with this being undefined/undefined context

CHANGELOG.md, spec/main.spec.js, src/builder.js
fixes https://github.com/honeybadger-io/honeybadger-react/issues/29
This should allow for the following use case:
let err = new Error('message');
err.context = { key1: 'value1' };
Honeybadger.notify(err, { context: { key2: 'value2' } });
=> Merge context from error objects

CHANGELOG.md, spec/main.spec.js, src/builder.js
**READY**
This PR fixes a bug in the `beforeNotify` logic where many notice properties were not passed in to the handler as documented:
https://docs.honeybadger.io/lib/javascript/guides/filtering-sensitive-data.html
Properties (such as `notice.url` could be assigned, but prior values were not available on the object to inspect, causing (i.e.) this example to fail:
```js
Honeybadger.beforeNotify(function(notice) {
if (/creditCard/.test(notice.url)) { // <-- notice.url is undefined
notice.url = '[FILTERED]'; // <-- works, but doesn't get here
}
});
```
This PR also hides the internal stack trace `generator` properties, which were previously exposed through the `notice` (or would have been ;)).
```bash
git pull --prune
git checkout …
```
=> Fix before notify props

CHANGELOG.md, spec/main.spec.js, src/builder.js
**READY**
This PR adds support for reporting unhandled promise rejections, as described in Issue #133.
In short, this PR adds a listener to `window.onunhandledrejection`, which gets invoked when a promise rejection is not handled with either `try...catch` or `Promise.catch()`. This might happen if an un-expected runtime error occurs, such as as an null pointer exception, or not handling a normal Promise rejection. The normal `window.onerror` handler will NOT be invoked in these cases. Here are some examples.
```js
fetch('/api/user/123')
.then(data => {
// User 123 does not have any data, but the API call returned a 200. So data = {}
let name = data.profile.name // 💥TypeError: Cannot read property 'name' of undefined
})
```
```js
let stuff = undefined
new Promise((resolve, reject), () => { …
```
=> Report unhandled promise rejections #133

honeybadger-js.d.ts
**READY**
I was trying to add this configuration to our app, but TypeScript complained that `'maxErrors' does not exist in type 'Config'`.
=> add maxErrors to type definition for config

honeybadger-js.d.ts
**READY**
In order to align types with documentation about [sending-request-information]( https://docs.honeybadger.io/lib/javascript/guides/customizing-error-reports.html#sending-request-information ) we need to add `cookies` as possible parameter of `Notice` interface.
>Note: I can't really fill in the todo's as this is just a type extending
=> chore: add cookies to Honeybadger types

spec/util/sanitize.spec.js, src/util/sanitize.js
Not sure if this is the right solution to nulls being included in sanitized arrays, but nulls are erroring because they are of an "object" type, yet don't implement `hasOwnProperty`
=> Deal with nulls in array

CHANGELOG.md, spec/main.spec.js, src/builder.js
See https://github.com/honeybadger-io/honeybadger-js/issues/266
This adds an additional check to make sure that the err.message object
can be tested against a regexp.
=> Fix n.match is not a function error w/ ignorePatterns

CHANGELOG.md, honeybadger-js.d.ts
Typescript compiler fails with an error if trying to use `onunhandledrejection`
**READY**
Allow `onunhandledrejection` to be used in Typescript projects when calling `Honeybadger.configure`
=> Add onunhandledrejection to Config interface type definition

spec/main.spec.js, src/builder.js
**WIP**
Add a hook to execute handlers after the request was sent.
#86  
I used the onload callback from XMLHttpRequest but I'm not sure If that's what you want?
I also pass the response to the handler but maybe we should also pass the payload sent?
=> feat(after-notify): hook to execute handlers after the request was sent

honeybadger-js.d.ts
**READY**
Fixes the following error when running type checks on a project that uses Honeybadger:
TS2339: Property 'addBreadcrumb' does not exist on type 'typeof Honeybadger'.
=> Add definition for Honeybadger.addBreadcrumb

CHANGELOG.md, spec/main.spec.js, src/builder.js
This makes two important changes:
1. Breadcrumbs auto-instrumentation is now performed on first `Honeybadger.configure` call, instead of on import.
For now, `window.onerror` and other pre-breadcrumbs instrumentation is still performed on import due to architectural limitations. This is something we may be able to change in the next version of the library which is currently in-progress.
2. The `breadcrumbsEnabled` option has been enhanced to support an object syntax so that individual breadcrumbs instrumentation types (such as "console") may be disabled. `breadcrumbsEnabled: true` and `breadcrumbsEnabled: false` will also continue to work.
Fixes #397
=> Instrument on first Honeybadger.configure call

CHANGELOG.md, src/builder.js
This allows the referrer and userAgent strings to be filtered in `beforeNotify` handlers:
https://docs.honeybadger.io/lib/javascript/guides/filtering-sensitive-data.html
=> Add referrer and userAgent to notice object

honeybadger.d.ts, src/browser.ts, src/core/client.ts, src/core/types.ts, src/core/util.ts, test/unit/core/client.test.ts, test/unit/server.test.ts
=> Disable honeybadger.js in development environments

honeybadger.d.ts, src/browser.ts, src/browser/integrations/onerror.ts, src/browser/integrations/onunhandledrejection.ts, src/core/client.ts, src/core/types.ts, src/server.ts, src/server/integrations/uncaught_exception.ts, src/server/integrations/unhandled_rejection.ts, src/server/util.ts, test/unit/browser.test.ts, test/unit/browser/integrations/onerror.browser.test.ts
This also renames the `onerror` config option to `enableUncaught`, which is more descriptive, and also makes more sense in node environments (which have a global `uncaughtException` event instead of `window.onerror`.)
Also adds `unhandledRejection` for node and renames the config option `onunhandledrejection` to `enableUnhandledRejection`.
=> Add uncaughtException server plugin for node

src/browser.ts, test/integration/test.js
`Honeybadger.wrap` was [initially requested](https://github.com/honeybadger-io/honeybadger-js/issues/17) to wrap jquery callbacks, and has been a pain to support for various reasons—[especially for Node](https://github.com/honeybadger-io/honeybadger-node/pull/13).
Because the initial use case was so simple, it's not useful on Node, and I'm not sure how useful it is for browsers anymore, I'm going to try removing it in the new universal Honeybadger JS, and see what happens. ;)
For those who still want this feature, it's basically this:
```js
Honeybadger.wrap = function(func) {
try {
func.apply(this, arguments)
} catch(error) {
Honeybadger.notify(error)
throw(error)
}
}
```
=> Remove public Honeybadger.wrap function

honeybadger.d.ts, test-d/browser.test-d.tsx
**READY**
This PR updates the types for the `breadcrumbsEnabled` prop to make all members optional.
For example —
```javascript
Honeybadger.configure({
apiKey: HONEYBADGER_API_KEY,
environment: HONEYBADGER_ENVIRONMENT,
revision: RELEASE_ID,
breadcrumbsEnabled: {
console: true,
},
});
```
is a valid configuration, but the latest version complains about this, expecting all other members of `breadcrumbsEnabled` to be defined as well.
List related PRs against other branches:
branch | PR
------ | ------
NA | NA
```bash
> git pull --prune
> git checkout <branch>
> grunt jasmine
```
1. See above.
=> types: Make sure every breadcrumb prop is optional

honeybadger.d.ts
**READY**
Fixes https://github.com/honeybadger-io/honeybadger-js/issues/539.
We're using a TypeScript-based Node framework ([Nest](nestjs.com)) and we need to use Honeybadger as the error reporting lib. However we can't set up the Honeybadger middleware `requestHandler` and `errorHandler` functions due to no types for them.
We don't actually need the `lambdaHandler` type but figured I'd go ahead and add that in here as well while I was at it.
I tested this out by linking locally to our project and ensuring the app compiled.
=> Add server middleware signatures to type declarations

src/browser/integrations/onunhandledrejection.ts, test/unit/browser/integrations/onunhandledrejection.browser.test.ts
**WIP**
Resolves issue with undefined message when unhandled promise is rejected without a reason.
See https://github.com/honeybadger-io/honeybadger-js/issues/534
See issue link above.
=> unhandled promise default reason

ship.config.js
**READY?**
https://github.com/honeybadger-io/honeybadger-js/issues/530
If commits are ready to release, the `commitNumbersPerType` object will have properties like `{ feat: 2, fix: 4, chore: 8 }`. If there are no changes, the object is empty. 
This took a little longer than expected to sort out since ShipJS was not running the `shouldPrepare` callback when `--dry-run` flag was used. I checked with the maintainers and have submitted a PR to change this behavior.
I haven't managed to generate a "positive" test (i.e. have commits to push), but all the tests run fine!
=> Do not prepare PR if no commits

CHANGELOG.md, honeybadger.d.ts, src/core/client.ts, src/core/types.ts, test/unit/core/client.test.ts
READY
Adds support for tags. I wasnt sure how to add to the honeybadger docs to reflect these changes.
You can now add tags 3 ways:
```js
Honeybadger.configure({
tags: "1, 2, 3"
})
const client = Honeybadger.configure()
client.setContext({tags: ["1", "2", "3"]})
client.notify("testing", {tags: "1, 2, 3"})
```
```bash
> git pull --prune
> git checkout <branch>
> npm run test
```
=> feat: add support for tags

honeybadger.d.ts
**WIP**
#540 added server middleware, but didn't add types to those functions.  In projects where TypeScript has `"noImplicitAny": true`, the compiler errors on those functions.
This PR:
- adds the `express` types to the parameters for those middleware functions
- explicitly sets `any` to types I didn't know offhand.
1. Create a new TypesScript project with `"noImplicitAny": true`.
2. `yarn add @honeybadger/js`
3. import Honeybadger into a module and use it
4. Run `./node_modules/.bin/tsc --noEmit`, with this branch, you should receive no errors.
=> Use express types for middleware

CHANGELOG.md, honeybadger.d.ts, test-d/browser.test-d.tsx, test-d/server.test-d.tsx
Fixes #609 
Addendum: Any reason why we manually write the typedefs? Methinks we could use tsc to generate them. thereby keeping them in sync with any code changes.
=> Add missing methods to typedefs

CHANGELOG.md, README.md, honeybadger.d.ts, package-lock.json, package.json, rollup.config.js, scripts/copy-typedefs.js, src/browser.ts, src/core/client.ts, src/core/types.ts, src/core/util.ts, src/server.ts, src/server/integrations/unhandled_rejection.ts, src/server/middleware.ts, src/server/util.ts, test-d/browser.test-d.tsx, test-d/server.test-d.tsx, test/unit/core/util.test.ts, test/unit/helpers.ts, tsconfig.json
(Apologies for the size of the PR; the changes involved turned out to be a little more than anticipated.)
This PR:
1. Adds `@types/express` to our dependencies, fixing #604 
2. Adds some missing null checks. A number of places had a check for `if (typeof thing === 'object')`, with the subtle bug that `null` in JS also returns `object`.
3. Improves typing. A number of types (some of which were user-facing) were incorrect or incomplete. I've fixed them so they're (mostly) correct, providing better IDE suggestions.
4. Switches to (mostly) automated generation of type declarations. This is done by enabling declarations in our `tsconfig.json`, then updating our Rollup config to point to the right paths for each build. However, this generates separate type decl files for the two builds, so …
=> Improve TypeScript usage

src/core/client.ts, src/core/util.ts, test/unit/core/client.test.ts, test/unit/core/util.test.ts
Debug logs are now logged at the default level in Chrome, so that you
don't have to enable verbose logging to see them (you still need to
configure the `debug: true` option.
Also changed a few of the log/error messages and used separate messages
for the development mode notice vs. disabled via `reportData: false`.
Closes #661
Edit: this also includes the notice in log messages, when available:
=> Improve dev-mode logging

CHANGELOG.md, src/core/client.ts, test/unit/core/client.test.ts, test/unit/server.test.ts
**READY**
Related Issue: #327 
I came up with a simple implementation of notify that returns a promise (notifyAsync).
It all became simple because now we always call the `afterNotify` hook, so I used it to know when to resolve/reject the promise.
I decided to go for this because of our recent work on AWS Lambda (see [here](https://github.com/honeybadger-io/honeybadger-js/issues/682#issuecomment-1013654404) and [here](https://github.com/honeybadger-io/honeybadger-js/pull/680#issuecomment-1008439277)). The _fire-and-forget_ approach does not work well with Lambda functions.
Let me know what you think.
Note: The target branch is [aws_lambda_async_#677](https://github.com/honeybadger-io/honeybadger-js/tree/aws_lambda_async_%23677)
=> #327 notifyAsync

CHANGELOG.md, src/core/util.ts, test/unit/core/util.test.ts
This is for a customer issue where we can't reproduce the specific error, but I'm pretty sure something in the data passed to breadcrumbs (via `console.log`) is blowing up the sanitize function.
I created a v3-stable base branch so that I can release immediately. I'll also add it to the main (v4) branch after this is merged.
=> Catch unknown errors in data sanitizer

CHANGELOG.md, src/core/client.ts, test/unit/core/client.test.ts
Also adds support for space-delimited tags; these strings are
equivalent:
- "one, two, three"
- "one two three"
- "one, two three"
This is a change I recently made to honeybadger-ruby (https://github.com/honeybadger-io/honeybadger-ruby/pull/422) and I realized we did the same thing here. I don't know why we were being so strict with the tag sanitizer, but I think this is better.
eslint also made some formatting changes, sorry about the noise.
=> Allow special characters in tags

src/core/util.ts, test/unit/core/client.test.ts
READY
While working with Hapi, I noticed errors were simply being reported as `Error` with an empty message, even though they were actually instances of TypeError:
Turned out the `Object.prototype.toString.call()` check was returning `[object Object]` because Hapi instantiates errors in some weird ways, so we were treating it as a regular object, not an error. Adding a check for instanceof fixes it.
=> Properly handle Error-prototype objects

src/browser.ts, src/core/client.ts, src/server.ts
READY
Tiny logging improvement: print the full link to the reported error in the logs, like the Ruby library does.
=> Include reported error link in logs

CHANGELOG.md, examples/express/index.js, package-lock.json, package.json, src/core/client.ts, src/core/store.ts, src/core/types.ts, src/server.ts, src/server/async_store.ts, src/server/aws_lambda.ts, src/server/integrations/unhandled_rejection.ts, src/server/middleware.ts, test/unit/core/client.test.ts, test/unit/server.test.ts, test/unit/server/backtrace.test.ts, test/unit/server/middleware.server.test.ts
READY
This PR fixes #708 by storing the context in [`AsyncLocalStorage`](https://nodejs.org/api/async_context.html) for web requests.
Thanks to the earlier work by @subzero10, the core implementation was relatively straightforward:
- First, when the agent is created, it uses the `GlobalStore` (renamed from `DefaultStore` so its behaviour is more obvious). This allows us to support simple single-request use cases like CLI jobs.
- We're exposing the `hb.run(cb)` method, which sets the store to the `AsyncStore` and runs the given code with it. Each request will have its own context, thanks to ALS. Users can wrap their request handlers in `hb.run()` to properly capture the context for each request. For supported frameworks like Express, they can just add the `Honeybadger.requestHandler` …
=> Implement context isolation for Node.js

src/core/client.ts, test-d/honeybadger.test-d.ts
**READY**
Fixes #736.
We are generating two sets of `.d.ts` files. It appears that when using the intersection type (`typeof Server & typeof Browser`) to export a Honeybadger typed singleton that supports both contexts, Typescript is complaining about the private variables because they come from different classes. These classes are the same but they come from different folders (`dist/browser/core/client.d.ts` and `dist/server/core/client.d.ts`). I think Typescript can't see that the variable is the same for both types, and assumes each type has their own unique private variable.
The easy solution without going too deep was to make this variable as `protected`, which is OK. The extending classes could use that variable (they don't use it now).
I feel that there may be a better way to …
=> #736 Fix typescript error with private variable

.github/workflows/shipjs-manual-prepare.yml, package-lock.json
Fixes shipjs prepare.
It broke because I merged a PR with a package-lock.json generated from npm 6. The workflow runs with npm 8 and this generated a new package-lock.json file which causes the release to fail (working tree is not clean).
=> Fix shipjs prepare

ship.config.js
Release was skipped because commit message did not match the expected format:
```
const correctCommitMessage = formatPullRequestTitle({
version: currentVersion,
});
if (!commitMessage.trim().startsWith(correctCommitMessage)) {
return (
'The commit message should have started with the following:' +
'\n' +
`${correctCommitMessage}`
);
}
```
I removed the custom commit message and pull request title from `ship.config.js`. The default ones use the conventional commits specification:
```
formatCommitMessage: ({ version, releaseType, baseBranch }) =>
`chore: release v${version}`,
formatPullRequestTitle: ({ version, releaseType }) =>
`chore: release v${version}`,
```
I think this is the final fix.
=> Fix shipjs config for conventional commits

CHANGELOG.md, examples/browserify/index.html, examples/browserify/main.js, examples/express/index.js, src/browser.ts, src/browser/transport.ts, src/core/client.ts, src/core/types.ts, src/core/util.ts, src/server.ts, src/server/transport.ts, src/server/util.ts, test/integration/sandbox.html, test/integration/test.js, test/unit/browser/integrations/onerror.browser.test.ts, test/unit/browser/integrations/onunhandledrejection.browser.test.ts, test/unit/browser/transport.browser.test.ts, test/unit/core/client.test.ts, test/unit/core/util.test.ts, test/unit/helpers.ts, test/unit/server.test.ts, test/unit/server/transport.server.test.ts
**READY**
Fixes #725 
In order to create a single `Honeybadger.checkIn()` method to be shared between browser and server, I decided to extract the transport layer logic into a separate interface. This way, we can abstract the browser vs server differences and implement a single `checkIn()` method to be used by both. I refactored `notify()` to use the same approach.
Notes:
- This is the first version of `Honeybadger.checkIn()` that simply pings Honeybadger from inside the code. There is ongoing discussion to add more features into this implementation (maintain/create check-ins through code).
- I noticed that the check-in API call does not require an API key, is that intended? Aren't there security concerns with this approach? @joshuap 
- The check-in API call will return HTTP OK even if …
=> #725 Honeybadger.checkIn()

src/core/client.ts
**READY**
As the comment in the code describes, we want to collect the backtrace before calling the `beforeNotifyHandler`s.
=> Collect backtrace before calling beforeNotifyHandlers

CHANGELOG.md, examples/aws-lambda/handler.js, examples/aws-lambda/serverless.yml, src/core/types.ts, src/server.ts, src/server/aws_lambda.ts, test/unit/server/aws_lambda.server.test.ts
**READY**
Fixes #679
Report to Honeybadger if AWS lambda function may possibly timeout.
=> #679 AWS Timeout Warning

src/core/types.ts, src/server/aws_lambda.ts
**READY**
Our d.ts files import types for `node v14` and `aws-lambda`. These deps are optional and this PR makes sure they don't cause type errors when Honeybadger is used with Typescript.
More on `ts-ignore` [here](https://github.com/microsoft/TypeScript/issues/29866#issuecomment-715140696).
More on `import type` [here](https://stackoverflow.com/a/63905376).
=> Improve typings for optional deps

packages/core/src/client.ts, packages/core/src/types.ts
**READY**
Refactor `notice.causes` outside the `Notice` type, since it's only used when sending the payload to Honeybadger.
=> chore: `notice.causes` refactor

packages/core/src/client.ts, packages/core/src/index.ts, packages/core/src/store.ts, packages/core/src/types.ts, packages/core/test/client.test.ts, packages/core/test/helpers.ts, packages/js/src/server.ts, packages/js/src/server/async_store.ts, packages/js/src/server/aws_lambda.ts, packages/js/src/server/stacked_store.ts, packages/js/test/unit/helpers.ts, packages/js/test/unit/server.test.ts, packages/js/test/unit/server/middleware.server.test.ts
Rework of https://github.com/honeybadger-io/honeybadger-js/pull/845, which should probably fix #905.
Going with @subzero10 's suggestion (thanks!), I've reworked the store API.
- No more singletons
- The store API is no longer just an extension of/workaround for AsyncLocalStorage, but an expression of where the Honeybadger client stores context and breadcrumbs. This means there's now a full-fledged Store interface:
```ts
interface HoneybadgerStore {
available(): boolean
getContents(): StoreContents
getContents<K extends keyof StoreContents>(key: K): StoreContents[K]
setContext(context: Record<string, unknown>): void
addBreadcrumb(breadcrumb: BreadcrumbRecord): void
clear(): void
run<R>(callback: () => R, ...opts: unknown[]): R
}
```
This gives us better encapsulation. Previously, the …
=> feat: rework store API

packages/js/README.md
Context: 
`import * as HoneyBadger from '@honeybadger-io/js'` as indicated in the documentation using nodejs + TypeScript results in errors such as 'configure' is not a function.
What really works in a nodejs + TypeScript context is using:
`import HoneyBadger from '@honeybadger-io/js'`
**READY**
A Change in the README.MD file to make it clear which is the right import statement to use while using ES6 imports + TypeScript
=> fix: README.md misleading dev to use wrong import code on while working with ES6 Import. 

packages/gatsby-plugin/gatsby-browser.js
**READY/WIP/HOLD**
Received error - Can't resolve 'honeybadger-js' in 'node_modules/@honeybadger-io/gatsby-plugin-honeybadger'
Changed the require statement to import from `@honeybadger-io/js`
List related PRs against other branches:
| branch              | PR       |
|---------------------|----------|
| other_pr_production | [link]() |
| other_pr_master     | [link]() |
```bash
> git pull --prune
> git checkout <branch>
> grunt jasmine
```
1.
=> fix: require correct honeybadger js package

packages/js/rollup.config.js, packages/js/src/server/integrations/uncaught_exception.ts, packages/js/src/server/integrations/unhandled_rejection.ts, tsconfig.base.json
**READY**
Fixes: #946.
I wanted to write tests but it seems that jest will exit the process without calling `process.on('unhandledRejection')`.
So, I tested manually with an example project.
I applied similar logic to `unhandledException`s for nodejs.
=> fix: exit process on unhandledRejection

.github/workflows/node.js.yml, packages/js/examples/.eslintrc.json, packages/react-native/example/.eslintrc.json, packages/vue/examples/.eslintrc.json
**READY**
Currently, running `npm run lint` fails locally unless you remember to install all the dependencies in each of the example folders, plus we have to install all those dependencies in CI. Since these are just the examples and not the main code, we can save time in CI and have fewer local errors during development if we selectively ignore these. 
```bash
npm run lint
```
1. You should not see errors, even if you neglected to `cd` into each example folder and `npm install`
2. CI should succeed without having to install these extra node modules just for linting
=> ci: ignore eslint imports in example folders

packages/rollup-plugin/README.md, packages/rollup-plugin/examples/rollup/rollup.config.mjs, packages/rollup-plugin/examples/vite-vue/vite.config.js, packages/rollup-plugin/src/hbUtils.js, packages/rollup-plugin/src/index.js, packages/rollup-plugin/src/options.js, packages/rollup-plugin/test/hbUtils.test.js, packages/rollup-plugin/test/index.test.js, packages/rollup-plugin/test/options.test.js, packages/webpack/README.md
READY
Adds the API call to send deployment notifications to Honeybadger via the Rollup plugin. Closes https://github.com/honeybadger-io/honeybadger-js/issues/1012. 
1. In `rollup-plugin` folder, run `npm install && npm run build`. 
2. In either of the example projects within `rollup-plugin`, run `npm install && npm run build`. You should see logging that the upload was successful and see the deploy appear in the UI: https://app.honeybadger.io/projects/[YOUR_PROJECT]/deploys
=> feat(rollup): add deployment notification to Rollup plugin

packages/react/src/HoneybadgerErrorBoundary.tsx, packages/react/src/index.test.tsx, packages/react/src/index.tsx
Fixes: #1020
**READY**
This was a brain teaser 😓 .
This PR fixes a bug I introduced with the release of the Collect User Feedback feature. The bug was introduced because I couldn't run the tests 🤦 .
- With the "Collect User Feedback", I added a new property in the react component to show the form automatically in case of an error (`showUserFeedbackForm`)
- I created a test for it, but it was failing with HTTP 403, even though I tried mocking the fetch api. I realised that it was importing the _server_ implementation of Honeybadger (as it is the main entry point of the `@honeybadger-io/js` package.
- So, since we always need the client side implementation, I changed the import to be explicit and imported `@honeybadger-io/js/dist/browser`.
- Hooray! My tests passed!
- Some frameworks use …
=> fix(react): import correctly @honeybadger-io/js

README.md
READY
Just noticed I forgot to link to the Rollup plugin from the monorepo README
=> chore(rollup): add rollup-plugin to the main README

.github/workflows/node.js.yml, packages/rollup-plugin/README.md, packages/rollup-plugin/package.json, packages/rollup-plugin/src/index.ts, packages/rollup-plugin/src/options.ts, packages/rollup-plugin/src/rollupUtils.ts, packages/rollup-plugin/src/types.ts, packages/rollup-plugin/test/fixtures/bundle.ts, packages/rollup-plugin/test/index.test.ts, packages/rollup-plugin/test/options.test.ts, packages/rollup-plugin/test/rollupUtils.test.ts
Fixes: #1053
**READY**
Add an option `ignorePaths` to allow ignoring certain paths from being uploaded as source maps.
=> feat: add ignorePaths option

packages/rollup-plugin/README.md, packages/rollup-plugin/package-lock.json, packages/rollup-plugin/package.json
READY
Document peer dependency of rollup v3: https://github.com/honeybadger-io/honeybadger-js/issues/1060 
Try changing the rollup version in a test project to rollup v2 and then run `npm i`. You'll get a peer dependency error.
=> fix(rollup-plugin): document rollup peer dependency

lerna.json
**READY**
Closes #957.
I first looked at the documentation which pointed to a very old package (supports up to lerna v2). Obviously, that didn't work.
Then, I simply tried setting `"version": "independent"` in `lerna.json`. To my surprise, it just works 🤷 
Here's the [dummy monorepo](https://github.com/subzero10/lerna-getting-started-example) I played with, and the published packages under an `hb-test` npm organization:
- [@hb-test/footer](https://www.npmjs.com/package/@hb-test/footer)
- [@hb-test/header](https://www.npmjs.com/package/@hb-test/header)
- [@hb-test/remixapp](https://www.npmjs.com/package/@hb-test/remixapp)
Notes:
- _footer_ and _header_ are dependencies of _remixapp_
- [git tags for releases](https://github.com/subzero10/lerna-getting-started-example/tags) are now created …
=> chore: switch to independent versioning

packages/core/package-lock.json, packages/core/src/util.ts, packages/js/package-lock.json, packages/js/tsconfig.json, packages/nextjs/tsconfig.json, packages/react/package-lock.json, packages/react/package.json, packages/react/tsconfig.json, packages/vue/package-lock.json
**READY**
I don't remember why, but the tsconfig.json files that have package dependencies within the monorepo were missing project references.
Project References are a handy Typescript feature that makes development easier by keeping the dependency package up-to-date with the latest changes while development.
For example, if I make a change in the core package, it should be available in the js package, just by building the js package (tsc will see that core is a dependency of the js package and would build it as well).
Note:
This is why we transpile typescript files before passing on to rollup; rollup does not work with project references.
=> chore: use project references correctly

packages/nextjs/README.md, packages/nextjs/src/copy-config-files.ts, packages/nextjs/templates/_error_app_router.js, packages/nextjs/templates/_error_app_router.tsx
Closes: #1070
**READY**
Adds support for the new [App Router in Next.js](https://nextjs.org/docs/app/building-your-application/routing#the-app-directory).
=> feat(nextjs): app router support

README.md
READY
We now use 'independent' mode for lerna, not 'fixed'.
=> docs: update release info in README

.gitignore, packages/js/test/integration/browsers.js
**READY**
Needed for https://github.com/honeybadger-io/docs/issues/243. 
My approach to picking the minimum browser versions were as follows: 
1. Must support fetch: https://caniuse.com/fetch
2. Must support let, var, const: https://caniuse.com/let
3. If the minimum version that met criteria 1 and 2 didn't pass integration tests, test a bunch of versions to find one that was released in 2018 or earlier and passed the tests. 
*Notes on criterion 3 above:*
Specifically, I had trouble with Firefox and Safari. 
*Safari*: 
- versions 10.1 on Sierra and 11.1 on High Sierra had a failure when testing a Web Worker
- specifically, [expect(results.notices.length).toEqual(1);](https://github.com/honeybadger-io/honeybadger-js/blob/0a9df3c0a2ffe13a08b8ce1a70aee901a50ac5fd/packages/js/test/integration/t …
=> chore(integration): test minimum browser version as well as latest

packages/js/src/server/integrations/uncaught_exception_monitor.ts, packages/js/src/server/integrations/uncaught_exception_plugin.ts, packages/js/test/unit/server/integrations/uncaught_exception_monitor.server.test.ts, packages/js/test/unit/server/integrations/uncaught_exception_plugin.server.test.ts
**READY**
Part of https://github.com/honeybadger-io/honeybadger-js/issues/1163
This PR makes it safe to load the uncaughtException plugin more than once. 
- If loaded with enableUncaught true, it will add a listener if one has not already been added
- If loaded with enableUncaught false, it will remove the listener if it exists
However, the client itself still only loads the plugin once, so this PR should not cause any user-facing change in behavior. 
Unit tests should mostly cover it. I also tested it by throwing an uncaught error in one of the example applications. I chose `sails`, but it could have been `express` or another node project. The trick is that you have to throw an error in a node application that is not covered by the honeybadger middleware, but also doesn't cause an import …
=> chore(js): allow uncaughtException plugin to be loaded more than once

packages/react/package.json, packages/vue/package.json
**READY**
Fixes #1175.
I think an older `@honeybadger-io/js` version is the cause of https://github.com/honeybadger-io/honeybadger-js/issues/1175 (waiting for user confirmation but it seems likely). 
https://github.com/honeybadger-io/honeybadger-js/pull/1107 started using `setNotifier()` but didn’t upgrade the peer dependency requirement. The change was released in 6.2.0: https://github.com/honeybadger-io/honeybadger-js/releases/tag/%40honeybadger-io/js%406.2.0
In the react example project, install a version of `@honeybadger-io/js` older than 6.2.0. You should see an error in the browser console related to `setNotifier()`. Installing version 6.2.0 should fix it.
=> fix(react/vue): update peer dep for vue and react

packages/js/src/server/integrations/unhandled_rejection_monitor.ts, packages/js/src/server/integrations/unhandled_rejection_plugin.ts, packages/js/test/unit/server/integrations/unhandled_rejection_monitor.server.test.ts, packages/js/test/unit/server/integrations/unhandled_rejection_plugin.server.test.ts
**READY**
Part of https://github.com/honeybadger-io/honeybadger-js/issues/1163
This PR makes it safe to load the unhandledRejection plugin more than once.
If loaded with enableUnhandledRejection true, it will add a listener if one has not already been added
If loaded with enableUnhandledRejection false, it will remove the listener if it exists
However, the client itself still only loads the plugin once, so this PR should not cause any user-facing change in behavior.
https://github.com/honeybadger-io/honeybadger-js/pull/1170 does the same with unhandledException
Unit tests mostly cover it, however I also tested manually using the `sails` example app. Any node-based example app would be fine, you just need to trigger a promise rejection where the middleware will not pick it up. eg
``` …
```
=> chore(js): allow unhandledRejection plugin to be loaded more than once

packages/core/src/client.ts, packages/core/src/types.ts, packages/core/test/client.test.ts, packages/core/test/helpers.ts
**READY**
Part of https://github.com/honeybadger-io/honeybadger-js/issues/1163
This PR allows a plugin to use an option `reloadOnConfigure` to be reloaded whenever `configure()` is called, rather than just once. 
Currently no plugins use this feature, but we plan to use this functionality in the server-side `js` package's `unhandledRejection` and `uncaughtException` plugins. 
~~- Documentation~~ The `__plugins` option appears to be undocumented (ie it does not appear [here](https://docs.honeybadger.io/lib/javascript/reference/configuration/#configuration-options), so I don't think this change requires documentation. 
```
npm run test
```
=> feat(core): optionally reload plugins

packages/react-native/README.md
**READY**
The docs repo does not want to use a `###` heading to pull an excerpt. I'd argue that the sourcemap section is large/important enough to warrant its own section anyway!
=> docs(react-native): sourcemaps in own section

packages/js/package-lock.json, packages/js/src/server/integrations/uncaught_exception_monitor.ts, packages/js/src/server/integrations/uncaught_exception_plugin.ts, packages/js/src/server/integrations/unhandled_rejection_monitor.ts, packages/js/src/server/integrations/unhandled_rejection_plugin.ts, packages/js/test/unit/server.test.ts, packages/js/test/unit/server/integrations/uncaught_exception_plugin.server.test.ts, packages/js/test/unit/server/integrations/unhandled_rejection_monitor.server.test.ts, packages/js/test/unit/server/integrations/unhandled_rejection_plugin.server.test.ts
**READY**
Part of https://github.com/honeybadger-io/honeybadger-js/issues/1163
Core version 6.3.0 includes the ability for plugins to set `shouldReloadOnConfigure`. This PR turns that on for the `unhandledRejection` and `uncaughtException` plugins. 
Listed in https://github.com/honeybadger-io/honeybadger-js/issues/1163 
```bash
cd packages/js
npm run test:server
```
=> feat(js): reload unhandledRejection and uncaughtException plugins on configure

packages/nextjs/package-lock.json, packages/nextjs/package.json, packages/nextjs/rollup.config.js, packages/nextjs/rollup.scripts.config.js, packages/nextjs/src/copy-config-files-exec.ts
**READY**
Fixes #1186.
I can't pinpoint how this broke, but I know that it was working before 😓 .
The issue is that the executable script is built with Typescript with a module target to esnext. Nodejs uses commonjs by default and we usually transform to commonjs when bundling with rollup. This PR adds a rollup config file to bundle the `honeybadger-copy-config-files` script in commonjs.
=> fix(nextjs): build copy files script as a commonjs module with rollup

.github/workflows/node.js.yml, packages/js/package-lock.json, packages/js/test/e2e/browsers.ts, packages/js/test/e2e/global-setup.ts, packages/js/test/e2e/global-teardown.ts, packages/js/test/e2e/playwright.config.ts
**READY**
A last minute change in #1171 broke the setup of the integration tests and they wouldn't exit the process when done.
=> ci(e2e): fix setup

packages/react-native/scripts/honeybadger-upload-sourcemaps.sh
**READY**
This PR fixes sourcemap generation for iOS builds with hermes enabled. Related issue: https://github.com/honeybadger-io/honeybadger-js/issues/1182
* From a test React Native app (0.72+, to make sure hermes is the default engine), install the Honeybadger RN library, initialize with your project API key and a unique revision string. 
```
Honeybadger.configure({ 
apiKey: '<your project API key>, 
revision: 'test-revision-1',
debug: true,
environment: 'production'
});
```
* Implement some code that will cause an exception. `throw new Error("test")` on a button press will work fine.
* Run the app in release mode. `npx react-native run-ios --mode Release`
* Generate and upload sourcemaps to Honeybadger. Make sure the --revision argument matches the revision in the initialization code. …
=> fix(react-native): fix sourcemaps for iOS builds with hermes

packages/webpack/README.md, packages/webpack/example/README.md, packages/webpack/example/index.html, packages/webpack/example/package-lock.json, packages/webpack/example/package.json, packages/webpack/example/src/index.js, packages/webpack/example/webpack.config.js, packages/webpack/package.json
**READY**
In working on https://github.com/honeybadger-io/honeybadger-js/issues/1013, I found I needed a basic project to test sourcemap upload and deploy notifications. I decided to set up the project first so I could see the behavior on the existing package before making changes. 
```bash
> cd packages/webpack/example
> npm i
> npm run build
```
You should see 
```
Uploaded main.js.map to Honeybadger API
Successfully sent deploy notification to Honeybadger API.
```
=> chore(webpack): set up basic example project to test plugin against

packages/js/src/server.ts, packages/js/src/server/util.ts, packages/js/test/unit/server.test.ts
**READY**
Configure Honeybadger using a config file (**server only**).
Closes: #1243
=> feat(js): read config from file

packages/plugin-core/src/sourcemaps.ts, packages/plugin-core/test/sourcemaps.test.ts
**READY**
`honeybadger-io/next` suggest to set the assetUrl to `https://my-app.vercel.app/_next` ([link](https://docs.honeybadger.io/lib/javascript/integration/nextjs/#configuration))
However, the plugin-core uses the `URL` class in a way that does not support this. Instead of overwriting the assetsUrl pathname, this PR joins them.
1. Follow the instructions at https://docs.honeybadger.io/lib/javascript/integration/nextjs
2. Observe that sourcemaps are not correctly uploaded including `_next` in the pathname
=> fix(plugin-core): support minified url creation with pathname in assetUrl

packages/js/package-lock.json, packages/js/package.json, packages/js/test/e2e/browserstack.config.ts
**READY**
It appears that e2e tests stopped working; they appear to be running forever. I am trying a few solutions in this PR.
I tried:
- manually setting the `playwrightVersion` for BrowserStack through `browserstack.playwrightVersion`. It didn't work, because [apparently BrowserStack first looks at browser version when selecting the playwrightVersion to run](https://www.browserstack.com/docs/automate/playwright/browsers-and-os#specify-playwright-version).
=> ci: fix integration tests

packages/js/examples/aws-lambda-typescript/app/handler.ts, packages/js/examples/aws-lambda/handler.js, packages/js/examples/aws-lambda/package-lock.json, packages/js/examples/aws-lambda/package.json
**READY**
The `aws-lambda` example used to work with Serverless's UI, but now their UI is going through a _revamping phase_ and it's unavailable. As an alternative to test the example project, I used Postman and to make things easier I modified the project to handle cases whether the payload is a JSON string.
=> chore: update aws-lambda example

packages/js/examples/checkins-manager/package-lock.json, packages/js/package-lock.json, packages/js/package.json, packages/js/rollup.config.js, packages/js/rollup.scripts.config.js, packages/js/src/server/util.ts, packages/js/test/e2e/integration.spec.ts, packages/js/test/unit/server.test.ts, packages/js/test/unit/server/check-ins-sync.test.ts
**READY**
Fixes: #1264
Replaces cosmiconfig with a simpler implementation.
=> fix: replace cosmiconfig with custom implementation

packages/js/README.md
**READY**
Adds a small text block in the README file with the process I used to _fix_ integration tests. As long as it's a simple matter of updating dependencies, I'm happy to keep using Playwright and BrowserStack together, but if it becomes more complicated, we may have to consider alternative solutions.
=> chore: add troubleshooting section for e2e integration tests

.eslintrc, eslint-local-rules.js, package-lock.json, package.json, packages/react-native/src/transport.ts
**READY**
Fixes: #1278.
- Removes an erroneous `jest-fetch-mock` import that was added by mistake in a source file.
- Also creates a custom eslint rule that will prevent similar errors in the future.
=> fix(react-native): remove wrong jest import

packages/js/package-lock.json, packages/js/package.json, packages/js/rollup.config.js, packages/js/rollup.scripts.config.js
**READY**
Fixes: #1288
We replaced the [cosmiconfig dependency](https://github.com/honeybadger-io/honeybadger-js/pull/1268) with an in-house solution, but we never removed the dependency from package.json. I was under the impression it was removed, but it's still there 🤷.
=> fix: remove unused cosmiconfig dependency

packages/core/src/client.ts, packages/core/src/defaults.ts, packages/core/src/index.ts, packages/core/src/plugins/events.ts, packages/core/src/throttled_events_logger.ts, packages/core/src/types.ts, packages/core/src/util.ts, packages/core/test/client.test.ts, packages/core/test/helpers.ts, packages/core/test/plugins/events.test.ts, packages/core/test/throttled_events_logger.test.ts, packages/core/test/util.test.ts, packages/js/examples/express/index.js, packages/js/src/browser.ts, packages/js/src/browser/integrations/breadcrumbs.ts, packages/js/src/browser/integrations/event_listeners.ts, packages/js/src/browser/integrations/onerror.ts, packages/js/src/browser/integrations/onunhandledrejection.ts, packages/js/src/browser/integrations/timers.ts, packages/js/src/browser/transport.ts, packages/js/src/browser/util.ts, packages/js/src/server.ts, packages/js/test/unit/server.test.ts
**READY**
Closes #1258.
- Adds `event` method, which replaces logEvent to match Client Library Spec. The already existing `logEvent` method is marked as deprecated.
- `Honeybadger.event` method will send `event_type` and `ts` by default.
- Console instrumentation for both client and server (nodejs).
=> feat: events api improvements

packages/nextjs/src/index.ts
**READY**
Fixes #1351.
Adds `@honeybadger-io/js` to external packages, since it uses Node.js `require` to import configuration files dynamically.
=> fix(nextjs): add honeybadger in external packages

packages/nextjs/src/index.ts
**READY**
When creating a new `entry` for webpack configuration, we are passing the `originalEntry` so we can merge with Honeybadger's configuration. If we are not setting any Honeybadger configuration, the `originalEntry` must still be evaluated since its result is used in the new `entry`.
Fixes: #1348.
=> fix(nextjs): return the correct result if file is missing

packages/js/src/server/transport.ts
**READY**
The `ServerTransport` class is used to make HTTP requests from nodejs. Inside this class we have a single `logger.debug` method call. When calling the `ServerTransport.send`, we _should_ pass in the logger instance from the original Honeybadger instance. This ensures whatever logger was configured by the user is propagated downstream.
This class is used by the [Honeybadger.notify](https://github.com/honeybadger-io/honeybadger-js/blob/1ee0a9ffcba28b89bae06a84cfa0ebe4d9b39612/packages/core/src/client.ts#L458) and [Honeybadger.event](https://github.com/honeybadger-io/honeybadger-js/blob/1ee0a9ffcba28b89bae06a84cfa0ebe4d9b39612/packages/core/src/client.ts#L321) methods. `Honeybadger.event` uses a `ThrottledEventsLogger` class to send events in batches, which we pass down Honeybadger …
=> fix(js): remove logger.debug from transport layer

package.json, packages/js/package-lock.json, packages/js/package.json, packages/js/rollup.scripts.config.js, packages/js/scripts/check-ins-sync-bin.js, packages/js/src/server/check-ins-sync-exec.ts, packages/nextjs/package-lock.json, packages/nextjs/package.json, packages/nextjs/rollup.scripts.config.js, packages/nextjs/scripts/copy-config-files-bin.js, packages/nextjs/src/copy-config-files-exec.ts, packages/plugin-core/package-lock.json, packages/plugin-core/rollup.config.mjs, packages/react-native/package-lock.json, packages/react/package-lock.json, packages/rollup-plugin/package-lock.json, packages/vue/package-lock.json, packages/webpack/package-lock.json, scripts/clean-repo.sh
**READY**
I noticed the CI [failing](https://github.com/honeybadger-io/honeybadger-js/actions/runs/8491109872/job/23262781296?pr=1325) recently.
Lerna is not working well with our "bin" scripts and this is a known [issue](https://github.com/lerna/lerna/issues/1444). 
Locally, Lerna will install packages, symlink the ones that are inside the monorepo and finally run build scripts (such as Typescript compilation and Rollup bundling).
While symlinking (which happens before build), it will also symlink bin executables. Until now, those bin executables were not available at this phase, as they would have been generated later by the Typescript compilation.
A workaround is to make sure that these "bin" scripts are always available and not rely on the "build" script. To do this, we point to raw …
=> fix(js): bin files as javascript

packages/esbuild-plugin/README.md, packages/rollup-plugin/README.md, packages/webpack/README.md
**READY**
Adds info about EU endpoints.
=> docs: provide info for EU endpoints

packages/esbuild-plugin/README.md, packages/esbuild-plugin/src/index.ts, packages/plugin-core/src/options.ts, packages/plugin-core/src/types.ts, packages/plugin-core/test/options.test.ts, packages/rollup-plugin/README.md, packages/rollup-plugin/src/index.ts, packages/rollup-plugin/src/rollupUtils.ts, packages/rollup-plugin/test/index.test.ts, packages/rollup-plugin/test/rollupUtils.test.ts, packages/rollup-plugin/tsconfig.json, packages/webpack/README.md, packages/webpack/src/HoneybadgerSourceMapPlugin.js, packages/webpack/test/HoneybadgerSourceMapPlugin.test.js
**READY**
Adds a configuration source map plugin option `developmentEnvironments`, similar to what we have for the [core plugin](https://github.com/honeybadger-io/honeybadger-js/blob/54c1fdb9823058281d14270576401d233c919958/packages/core/src/defaults.ts#L17). The sole purpose of this option is to be used in order to decide whether source maps should be uploaded or not.
Closes #1408.
=> feat: adds configurable dev environments for source map upload plugins

packages/plugin-core/src/sourcemaps.ts
**READY**
Prints a message on successful source maps upload to remind users that Honeybadger needs to be configured with the same revision in order for source maps to match.
Closes: #1417
=> chore(plugin-core): print source map revisions message

.github/workflows/node.js.yml
**READY**
Removes v14 - first step of upgrading version matrix in CI (see #1421).
Part of #1421.
=> ci: remove node 14 from matrix

.github/workflows/node.js.yml, packages/js/src/server/integrations/uncaught_exception_monitor.ts, packages/js/src/server/integrations/unhandled_rejection_monitor.ts, packages/js/src/server/util.ts, packages/js/test/unit/server/integrations/uncaught_exception_monitor.server.test.ts, packages/js/test/unit/server/integrations/unhandled_rejection_monitor.server.test.ts
**READY**
Before exiting the process due to uncaught process exceptions or unhandled promise rejections we were logging the same error message, which recently cost hours of debugging for a customer. This should make it easier to identify whether the error originated from (uncaught exception or unhandled rejection).
=> fix(js): improved, unambiguous error message

packages/js/package-lock.json, packages/js/package.json
**READY**
Upgrades to _playwright@1.51_ (latest) that uses the new chrome headless browser. This fixes the failing CI tests.
=> ci: upgrade playwright to use new chrome headless

packages/core/src/client.ts, packages/core/src/throttled_events_logger.ts, packages/core/src/types.ts, packages/js/src/server.ts, packages/js/src/server/integrations/shutdown_monitor.ts, packages/js/src/server/integrations/shutdown_plugin.ts, packages/js/src/server/integrations/uncaught_exception_monitor.ts, packages/js/src/server/integrations/unhandled_rejection_monitor.ts, packages/js/src/server/util.ts, packages/js/test/e2e/playwright.config.ts, packages/js/test/unit/server.test.ts, packages/js/test/unit/server/integrations/shutdown_monitor.server.test.ts, packages/js/test/unit/server/integrations/shutdown_plugin.server.test.ts
**READY**
Closes: #1429
Adds listeners for `SIGTERM` and `SIGINT` process events. When we add listeners for such events we have to exit the process. Similar to other listeners (uncaughtException), first I check if there are other listeners attached as well before exiting.
=> feat: flush events on process exit

packages/vue/src/index.js
**READY**
Fixes: #1427
After some research online, it seems that it's possible for `vm` to be undefined when the component being rendered is _anonymous_. This can vary depending on the vue.js version being used, how the component is being defined and how it's being imported. I don't have a definite reproducible example yet, but I'm pretty sure this fix should cover it.
=> fix(vue): handle anonymous components

packages/esbuild-plugin/src/index.test.ts, packages/esbuild-plugin/src/index.ts
**READY**
Fixes #1426.
In most cases, the resulting file path (found in `result.outputFiles`) is the correct path.
For example, the following [@nx/esbuild](https://nx.dev/technologies/build-tools/esbuild/api/executors/esbuild) configuration works without the need to overwrite the output path.
```
/**
* "build": {
*       "executor": "@nx/esbuild:esbuild",
*       "options": {
*         "main": "apps/app/src/main.ts",
*         "tsConfig": "apps/app/tsconfig.app.json",
*         "outputPath": "dist/apps/app"
*       }
*     }
*/
```
However, when used with @nx/angular:application as an esbuild plugin, it seems that the `outputPath` configuration is not propagated to the esbuild plugin. This PR addresses this limitation by allowing to pass a value to overwrite the output path:
```
// …
```
=> feat(esbuild-plugin): add support for custom output path
