- honeybadger-js.d.ts
Updates "honeybadger-js".Config interface to use camelCase key names
> Update HB typescript definitions for config opts

- honeybadger.js
Why:
* receiving undeclared variable errors upon
instantiating as a module in a react app using webpack 2
Changes:
* added var declarations in various places in source code
where needed.
> Add variable declarations

- honeybadger-js.d.ts
Missing options:
- debug
- revision
- ignorePatterns
- async
> Add missing configuration options to TS type definition

- CHANGELOG.md
- Gruntfile.js
- README.md
- honeybadger.js
- package.json
- spec/honeybadger.spec.js
@josh here's my implementation for issue `Add option to limit errors sent per page load` #79. Let me know if the naming of functions and variables are acceptable, the commits in the PR are clean and I can easily rebase in name changes.
> Limit errors sent per page load

- honeybadger.js
Fixes #88 without relying on function.bind
I think I switched the `this` usages correctly.
> Fix for console binding

- CHANGELOG.md
- package.json
> Add TypeScript type definitions file to package.json

- scripts/release-cdn.sh
**READY**
Add cache-control header to objects on s3 so cloudfront will pass it along to browsers.
> Add cache-control header

- CHANGELOG.md
- src/builder.js
This should fix https://github.com/honeybadger-io/honeybadger-js/issues/242
> Unwrap functions before instrumenting

- honeybadger-js.d.ts
**READY**
It appears there are a bunch that are missing, but these are the ones that came up for us while converting our code to TypeScript.
> add a few more keys to type definitions

- CHANGELOG.md
- honeybadger-js.d.ts
Fixes #279
Related: https://github.com/honeybadger-io/honeybadger-react/pull/91
**READY**
Fixes a few incorrect return types.
> Fix TypeScript type definitions

- honeybadger-js.d.ts
READY
Add `breadcrumbsEnabled` to TS definition file.
- ~[ ] Tests~
- ~[ ] Documentation~
1. Install honeybadger-js in a TS app
2. Add `breadcrumbsEnabled: true` to configuration
```
Argument of type '{ ... breadcrumbsEnabled: boolean }' is not assignable to parameter of type 'Config'.
Object literal may only specify known properties, and 'breadcrumbsEnabled' does not exist in type 'Config'.
```
> Add breadcrumbsEnabled to TypeScript definition file

- honeybadger-js.d.ts
> Fix: Type definition incorrect for resetContext

- CHANGELOG.md
- src/builder.js
Fixes #340
Docs:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
> Replace use of for...in over Array

- honeybadger.d.ts
- src/core/client.ts
- src/core/types.ts
- src/core/util.ts
- test/unit/core/client.test.ts
This adds the `config.filters` option from [honeybadger-node](https://github.com/honeybadger-io/honeybadger-node#advanced-configuration).
> Filter sensitive keys in params and cgiData

- honeybadger.d.ts
- src/core/client.ts
- src/core/types.ts
- src/core/util.ts
- test-d/browser.test-d.tsx
- test/unit/core/util.test.ts
> Remove ignorePatterns feature

- src/browser.ts
- src/browser/util.ts
- test/unit/browser.test.ts
> Filter cookie values

- src/core/client.ts
- src/core/util.ts
- test/unit/core/client.test.ts
- test/unit/core/util.test.ts
> Filter URL params

- CHANGELOG.md
- src/server.ts
> utf8 encode JSON payload in Node

- CHANGELOG.md
- examples/express/README.md
- examples/express/index.js
- examples/express/package-lock.json
- examples/express/package.json
- src/core/client.ts
- src/server/middleware.ts
- test/unit/core/client.test.ts
- test/unit/server.test.ts
This should allow people to clear the context and breadcrumbs in between requests (in Express, for instance).
> Add clearContext method to clear context and breadcrumbs

- ship.config.js
> [Shipjs] Don't prepare release if there are no unreleased changes

- CHANGELOG.md
- src/core/client.ts
- src/core/types.ts
- test-d/browser.test-d.tsx
- test-d/server.test-d.tsx
- test/unit/core/client.test.ts
> Remove deprecated disabled config option

- CHANGELOG.md
> fix: cleanup CHANGELOG.md file to use with conventional-changelog

- src/server/transport.ts
Workaround for [#825](https://github.com/honeybadger-io/honeybadger-js/issues/825#issuecomment-1193113433)
> Workaround for Node.js-patching libraries

- src/core/client.ts
- src/core/types.ts
- src/core/util.ts
- test/unit/core/client.test.ts
> Support nested exceptions (error.cause)

- tsconfig.base.json
**READY**
Reverts back to es5 transpilation because there were issues with some bundlers.
Fixes: #864
> fix: revert to es5 transpilation

- .eslintrc
- packages/webpack/.babelrc
- packages/webpack/.mocharc.yaml
- packages/webpack/CHANGELOG.md
- packages/webpack/README.md
- packages/webpack/package-lock.json
- packages/webpack/package.json
- packages/webpack/src/HoneybadgerSourceMapPlugin.js
- packages/webpack/src/constants.js
- packages/webpack/src/helpers.js
- packages/webpack/src/resolvePromiseWithWorkers.js
- packages/webpack/test/HoneybadgerSourceMapPlugin.test.js
- packages/webpack/test/fixtures/uncompiled.js
- packages/webpack/test/helpers.test.js
- packages/webpack/test/integration.test.js
- packages/webpack/test/resolvePromiseWithWorkers.test.js
**READY/WIP/HOLD**
I just realized that the version I released with the monorepo is outdated 😱 [Lerna import](https://www.npmjs.com/package/@lerna/import) did not work as expected!
> fix: release correct version, lerna import did not work

- .github/workflows/commitlint.yml
- .github/workflows/node.js.yml
- .husky/commit-msg
- package-lock.json
- package.json
> fix: only lint PR title format

- packages/webpack/package-lock.json
- packages/webpack/package.json
- packages/webpack/src/HoneybadgerSourceMapPlugin.js
**READY**
- Fix the bug with Rails webpacker compilation described here: #949 
Steps described in #949
> fix: webpack compilaton issues

- packages/webpack/README.md
**READY**
Tiny PR to fix broken links in webpack README
> docs(webpack): update documentation links in readme

- .github/PULL_REQUEST_TEMPLATE.md
- packages/core/src/client.ts
- packages/core/src/util.ts
- packages/core/test/client.test.ts
- packages/js/test/unit/server.test.ts
- packages/js/test/unit/server/backtrace.server.test.ts
- packages/js/test/unit/server/middleware.server.test.ts
> fix: filter out honeybadger source code from stack trace

- packages/react/package.json
- packages/vue/package.json
**READY**
First reported [here](https://github.com/honeybadger-io/honeybadger-js/pull/1019).
> fix: update peer deps

- README.md
**READY**
Add Next.js in README.
> chore: add Next.js package in README

- packages/js/src/browser/integrations/breadcrumbs.ts
- packages/js/src/browser/util.ts
**READY**
Follow up to this issue https://github.com/honeybadger-io/honeybadger-js/issues/1058
Here is explanation https://github.com/honeybadger-io/honeybadger-js/issues/1058#issuecomment-1522164267
> feat: support URL objects in XHR requests

- packages/react/package-lock.json
- packages/react/package.json
- packages/react/src/HoneybadgerErrorBoundary.tsx
- packages/react/src/index.test.tsx
> fix(react): update types to work with react 18

- .github/workflows/commitlint.yml
- .github/workflows/node.js.yml
**READY**
Detect if PR will introduce breaking changes which will cause a major version upgrade.
> chore(monorepo): detect changes that would cause major version bump

- packages/react/example/package-lock.json
- packages/react/package.json
READY
Closes https://github.com/honeybadger-io/honeybadger-js/issues/1098
Run example project. It seems to work fine with v6.
> chore(react): update peer dependency for react to use most recent js package

- packages/core/src/client.ts
- packages/core/src/types.ts
- packages/js/package-lock.json
- packages/js/package.json
- packages/js/src/browser.ts
- packages/js/src/server.ts
- packages/js/test/unit/browser.test.ts
- packages/js/test/unit/server.test.ts
- packages/react-native/package-lock.json
- packages/react-native/package.json
- packages/react-native/rollup.config.mjs
- packages/react-native/src/index.ts
- packages/react-native/src/transport.ts
- packages/react-native/test/index.test.ts
- packages/react-native/test/transport.test.ts
- packages/react/package-lock.json
- packages/react/package.json
- packages/react/rollup.config.js
- packages/react/src/index.test.tsx
- packages/react/src/index.tsx
- packages/react/tsconfig.json
- packages/vue/package-lock.json
- packages/vue/package.json
- packages/vue/rollup.config.js
- packages/vue/src/index.js
- packages/vue/test/unit/specs/HoneyBadgerVue.spec.js
**READY**
Closes: #1097
- ~~nextjs~~ Next.js uses the react client to report errors
> feat: specify notifier per package

- .github/workflows/node.js.yml
- packages/js/package-lock.json
- packages/nextjs/jest.config.js
- packages/nextjs/package-lock.json
- packages/nextjs/package.json
- packages/nextjs/rollup.config.js
- packages/nextjs/src/copy-config-files-exec.ts
- packages/nextjs/src/copy-config-files.test.ts
- packages/nextjs/src/copy-config-files.ts
> feat(nextjs): support project structure under src folder

- packages/core/src/client.ts
READY
Hoping this comment helps us remember next time we add a new notifier!
See https://github.com/honeybadger-io/honeybadger/pull/4065 and https://github.com/honeybadger-io/honeybadger/pull/4067.
> docs(core): add a note about adding notifiers

- packages/js/test/integration/browsers.js
**READY**
See https://github.com/honeybadger-io/docs/pull/318#issuecomment-1664064010 -- it's no big deal to update the docs, we just need to remember to do it!
https://github.com/honeybadger-io/docs/pull/318
> chore(docs): add reminder to update docs

- packages/js/examples/aws-lambda/handler.js
- packages/js/examples/aws-lambda/package-lock.json
- packages/js/examples/aws-lambda/package.json
- packages/js/examples/aws-lambda/serverless.yml
**READY**
Adds an example function that uses `notifyAsync`.
> chore: more example code

- packages/nextjs/package-lock.json
- packages/nextjs/package.json
**READY**
Update peer dep to support nextjs v14.
> chore(nextjs): update nextjs peer dep

- README.md
> chore: mention plugin-core in README

- packages/js/src/browser.ts
**READY**
Fixes a check for navigator; issue reported [here](https://github.com/honeybadger-io/honeybadger-js/issues/1264#issuecomment-1871964777).
> fix: improve check for navigator

- .github/workflows/commitlint.yml
**READY**
Stores the PR title in an environment variable before usage. This should prevent any unwanted remote code execution.
> ci: store pr title before usage

- packages/js/package-lock.json
- packages/js/package.json
**READY**
The latest version of Ubuntu and Playwright are not working very well. I am trying to pick a version of Playwright that works with it. I am following [this issue](https://github.com/microsoft/playwright/issues/30368#issuecomment-2413952525).
> ci: update playwright

- packages/nextjs/package-lock.json
- packages/nextjs/package.json
**READY**
Updates dependencies (include peer) for the nextjs package.
Fixes #1320.
> perf(nextjs): update dependencies

- packages/js/package-lock.json
- packages/js/package.json
**READY**
Closes: #1437
Updates to express types to v5. I tested with 2 example apps, one on express v4 (for backwards compatibility) and the other on express v5.
> perf(js): update express types
